#!/usr/bin/env python3

raw_specs = [
    'MulticastSocket_TTL', # if
    'RuntimePermission_NullAction', # condition
    'TreeSet_Comparable', # if
    'Long_BadDecodeArg', # if
    'Arrays_MutuallyComparable', # if
    'Runnable_OverrideRun', # if
    'Byte_BadDecodeArg', # if
    'Socket_TrafficClass', # if
    'Short_BadDecodeArg', # if
    'CharSequence_UndefinedHashCode', # call
    'InetSocketAddress_Port', # if
    'IDN_ToAscii', # if
    'SocketPermission_Actions', # if
    'Integer_BadDecodeArg', # if
    'Dictionary_NullKeyOrValue', # condition
    'ServerSocket_Timeout', # if
    'Authenticator_OverrideGetPasswordAuthentication', # if
    'Long_BadParsingArgs', # if
    'EnumSet_NonNull', # condition/if
    'NetPermission_Name', # if
    'SortedSet_Comparable', # if
    'CharSequence_NotInSet', # condition/if
    'InputStream_MarkReset', # ok
    'Random_OverrideNext', # if
    'Collections_UnnecessaryNewSetFromMap', # call
    'HttpCookie_Name', # if
    'Object_NoClone', # ignored
    'Short_BadParsingArgs', # if
    'Socket_Timeout', # if
    'ContentHandler_GetContent', # call
    'Comparable_CompareToNull', # if-pointcut
    'Arrays_Comparable', # if
    'HttpCookie_Domain', # if
    'Comparable_CompareToNullException', # condition/if-pointcut
    'ServerSocket_Backlog', # if
    'RuntimePermission_PermName', # if
    'URLEncoder_EncodeUTF8', # if
    'Collections_Comparable', # if
    'DatagramSocket_SoTimeout', # if
    'NetPermission_Actions', # if
    'Serializable_NoArgConstructor', # if
    'ArrayDeque_NonNull', # condition
    'EnumMap_NonNull', # condition/if
    'Enum_NoExtraWhiteSpace', # condition
    'DatagramSocket_Port', # if
    'String_UseStringBuilder', # call
    'Collections_CopySize', # condition
    'URLDecoder_DecodeUTF8', # if
    'DatagramPacket_Length', # if
    'Closeable_MeaninglessClose', # call
    'Character_ValidateChar', # if
    'URLConnection_OverrideGetPermission', # if
    'Arrays_DeepHashCode', # if
    'TreeMap_Comparable', # if
    'Set_ItselfAsElement', # condition/if
    'CharSequence_NotInMap', # condition/if
    'DatagramPacket_SetLength', # if
    'Object_MonitorOwner', # if-pointcut
    'DatagramSocket_TrafficClass', # if
    'System_NullArrayCopy', # condition
    'InvalidPropertiesFormatException_NonSerializable', # call
    'Map_ItselfAsValue', # if
    'ClassLoader_UnsafeClassDefinition', # condition
    'PriorityQueue_NonNull', # condition/if
    'Map_ItselfAsKey', # if
    'Collections_ImplementComparable', # if
    'Collection_HashCode', # if
    'InetAddress_IsReachable', # if
    'PriorityQueue_NonComparable', # if
    'Vector_InsertIndex', # if
    'Byte_BadParsingArgs', # if
    'Reader_MarkReset', # call
    'ServerSocket_Port', # if
    'File_LengthOnDirectory' # condition
]

raw_specs = set(raw_specs)

